version: '2'

services:
  parnika-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/websites/templates/:/etc/nginx/conf.d/:ro
      - ~/websites/html/:/usr/share/nginx/html/:ro
      - ~/websites/certs/:/etc/nginx/:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Kolkata
    #- NGINX_HOST=foobar.com
    #- NGINX_PORT=80
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/lifescience.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"