version: '2'

services:
  lifescience-web:
    image: nginx
    restart: always
    volumes:
      - ./lifescience.template:/etc/nginx/conf.d/lifescience.template
    ports:
    - "8086:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/lifescience.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"